### ISSUE TITLE
OAuth Crash

### ISSUE THREAD

**Issue by sabrehagen** [jbszczepaniak/spotify-cli#1] opened 2018-09-27 07:11 UTC
On Ubuntu 18.04, after receiving the OAuth redirect of
```
http://localhost:8888/spotify-cli?code=AQB9KRNPwgRsoP5vWerwi0mr0BpDMOwRuEVz-xWvO6Nq2KPEvA94aKEuz_8WQzkeMwKjCL5aYrFyVIobz29Gq8CnEwV6X84wpsdDZneeAC_766pu5jmHlXhQ9Wy8GJoLvNBgz-0CcriHdRwPLzg6A9sprG8JNkEijylYPUOHAXKmfri8RdMkapPwpf_R6P_q1uo6Dthz775mFt50wECCx-3GsX0m8YaHiPuByf3iDEhkjMkhiXkg7HHeaShgi5XwZGY7XfOVN17NwVoH4DfmgZwJJmN3u__tNfKbn7l0p1OnTa40RpBvl7WlgVQFuW9DDUar52TmrgA1xQl2BO1CvcRz5nASiAcA06Ka9yxkMx4gXIUJzPvvqqKvQJiNwICf-dNXV7GgpHMyJ84Gt1kDhHmF_NcHWvVJpAfkwSg8lgy8vz8&state=f3eee04d-57ee-43b5-8f83-f17d52666cc7
```

the terminal shows output of

```sh
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7ab604]

goroutine 1 [running]:
main.main()
        /home/jackson/go/src/github.com/jedruniu/spotify-cli/main.go:100 +0x514
```

**Comment by jedruniu** [comment] 2018-09-27 18:30
Does this happen all the time, or sometimes? What version of go do yo have?

**Comment by sabrehagen** [comment] 2018-09-27 23:08
All the time, and the head of master. `f24106a`

**Comment by jedruniu** [comment] 2018-10-03 18:00
Let me recheck.

**Comment by jedruniu** [comment] 2018-10-03 19:11
@sabrehagen  @snippins  **What browser do you use?** I have some issues when using Firefox, with Chrome it is all right. I created fresh Ubuntu 18.04 installation, I installed golang, and go `1.10.1 linux/amd64` was installed. I used my existing spotify application for spotify account that has premium, and it jusy works. It doesn't however work with Firefox as default browser - but I don't see any traceback, you just run and it doesn't do anything after authentication.

**Comment by snippins** [comment] 2018-10-04 02:36
Also music is still playing in my browser after the crash.

**Comment by jedruniu** [comment] 2018-10-04 07:29
I didn't try with `go get`, I was using README.md steps to install - but I will try `go get` as well. I will check today. As for music playing after crash - this is an issue - different one though.

**Comment by jedruniu** [comment] 2018-10-06 18:45
@snippins , @sabrehagen  Maybe I will release ready binaries if you have such problems? Because I really tried hard to reproduce this problem and I can't.

**Comment by sabrehagen** [comment] 2018-10-06 22:44
I'm happy to try those releases and report back.

**Comment by snippins** [comment] 2018-10-07 02:17
I'm happy to try those as well.

**Comment by jkawczynski** [comment] 2018-10-09 20:44
@sabrehagen @snippins I've tested this release, works well for me

**Comment by jedruniu** [comment] 2018-10-09 20:45
Please try to use spotify-cli for your flavor: https://github.com/jedruniu/spotify-cli/releases/tag/v1.0.1 Note that you still have to have proper spotify application configured.

**Comment by sabrehagen** [comment] 2018-10-09 23:16
I still get the following:
```sh
> ./spotify-cli 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7c9135]

goroutine 1 [running]:
main.main()
        /Users/jedrzejszczepaniak/go/src/github.com/jedruniu/spotify-cli/main.go:100 +0x555
```

**Comment by snippins** [comment] 2018-10-10 02:51
Exact same thing for me

```
 $ ./spotify-cli
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7c9135]

goroutine 1 [running]:
main.main()
        /Users/jedrzejszczepaniak/go/src/github.com/jedruniu/spotify-cli/main.go:100 +0x555
```

**Comment by jedruniu** [comment] 2018-10-16 20:02
Guys sorry but I can't reproduce it.

**Comment by jbszczepaniak** [comment] 2020-06-21 12:25
I fixed problems reported by users and [released new versions](https://github.com/jbszczepaniak/spotify-cli/releases/tag/v1.0.3)
Please consider using this one, also remember about [requirements](https://github.com/jbszczepaniak/spotify-cli/tree/v1.0.3#prerequisites) for running the project.
I am closing this issue, if running newest release will be still problematic for you - feel free to reopen the issue.

**Closed by jbszczepaniak** 2020-06-21 12:25 UTC
